### PR TITLE
🚧 Initial version

### PR DESCRIPTION
**Pull request by gr2m**
- [ ] Implement features. Create separate `feat: ...` commits for each feature of the initial version
- [ ] 100% test coverage
- [x] Install https://github.com/apps/greenkeeper
- [x] Install https://github.com/apps/pika-ci
- [x] Create npm token at `https://www.npmjs.com/settings/<your npm username>/tokens/create` (with "Read and Publish" selected) and add it as `NPM_SECRET` at Then create secret at https://github.com/octokit/plugin-paginate-graphql.js/secrets

See this comment for how we can build GraphQL pagination by utilizing a naming convention for cursor variables:
https://github.com/octokit/graphql.js/issues/61#issuecomment-643392492

Particularly

> Alternatively it could require a certain name for the cursor variable, such as `cursor_repository_stargazers`. The `graphqlPaginate` method could look for option variables starting with `cursor_` and derive the path to the paginating node from the name, so we could have the same method signature as `graphql(query, variables)`.

closes https://github.com/octokit/maintainers/issues/31

### CODE REVIEW

**Comment by dominguezcelada** [comment]
Hi @gr2m @NickLiffen ! Is this still a plan? Or it's too complicated to handle and there won't be an official pagination helper? https://github.com/octokit/graphql.js/issues/61#issuecomment-578543062

I would be interested in collaborate on it if it's going to move forward and if it's possible.

Thanks

**Comment by gr2m** [comment]
Right now I think it's too complicated. We'd probably be better of by creating good tutorials on how to paginate with the current `octokit.graphql` API. Once we have some good tutorials, we can try to find patterns that might be helpful to codify in a plugin.

**Comment by dominguezcelada** [comment]
> Right now I think it's too complicated. We'd probably be better of by creating good tutorials on how to paginate with the current `octokit.graphql` API. Once we have some good tutorials, we can try to find patterns that might be helpful to codify in a plugin. 

Yep,I read the thread on the original issue. I just wanted to know if there were news on this. Maybe this repo should be archieved?

Thanks for your answer!

**Comment by gr2m** [comment]
I didn't give up hope just yet. I intend to write some tutorials myself, unless someone beats me to it ;)

**Comment by dominguezcelada** [comment]
> I didn't give up hope just yet. I intend to write some tutorials myself, unless someone beats me to it ;)

I have zero knowledge on GraphQL right now but I’m catching up with it (as doing with TypeScript xD) so if you think I can help to draft these docs... I’m in! :)

**Comment by dominguezcelada** [comment]
> I didn't give up hope just yet. I intend to write some tutorials myself, unless someone beats me to it ;)

I have zero knowledge on GraphQL right now but I’m catching up with it (as doing with TypeScript xD) so if you think I can help to draft these docs... I’m in! :)

**Comment by gr2m** [comment]
Here is the recording of Rea's talk I mentioned in the thread at https://github.com/octokit/graphql.js/issues/61
https://www.youtube.com/watch?v=i5pIszu9MeM

Basically I'd convert these to a set of tutorials. Giving Rea full credit of course.

**Comment by dominguezcelada** [comment]
> Here is the recording of Rea's talk I mentioned in the thread at https://github.com/octokit/graphql.js/issues/61
> 
> https://www.youtube.com/watch?v=i5pIszu9MeM
> 
> 
> 
> Basically I'd convert these to a set of tutorials. Giving Rea full credit of course.

I watched the talk yesterday. Super cool talk. Ok about the tutorials but... not sure which structure to follow. Is there any other repo on Octokit with tutorials to follow the approach? 

I will draft an index proposal so we can start discussing it! :)

**Comment by gr2m** [comment]
> not sure which structure to follow. Is there any other repo on Octokit with tutorials to follow the approach

Not really, I wish there was though. I published a few tutorial-esque posts to https://dev.to/gr2m/. If you write some up we can just list them in the README.md of https://github.com/octokit/graphql.js for now

**Comment by dominguezcelada** [comment]
> > not sure which structure to follow. Is there any other repo on Octokit with tutorials to follow the approach
> 
> 
> 
> Not really, I wish there was though. I published a few tutorial-esque posts to https://dev.to/gr2m/. If you write some up we can just list them in the README.md of https://github.com/octokit/graphql.js for now

Sure! Let me draft some initial posts and we can discuss it together :)

**Comment by jetersen** [comment]
@gr2m we have this wonderful pagination script over at release-drafter:
https://github.com/release-drafter/release-drafter/blob/master/lib/pagination.js

Should be flexible enough for most cases. Apart from sub pagination but could properly be fixed easily.
See usage here: https://github.com/release-drafter/release-drafter/blob/master/lib/commits.js

**Comment by gr2m** [comment]
Thanks a lot for sharing Joseph! I've currently very limited availability, but I will get back to you. I'm looking forward to it!

**Comment by gr2m** [comment]
@jetersen I was wondering if we could avoid the extra `paginatePath` parameter by enforcing a naming convention of the cursor variables, see my comment here: https://github.com/octokit/graphql.js/issues/61#issuecomment-643392492

In the case of your query at https://github.com/release-drafter/release-drafter/blob/master/lib/commits.js, instead of using `$after`, the variable could be called `$cursor_repository_ref_target_history`. What do you think?

**Comment by jetersen** [comment]
@gr2m I am all for generalizing graphql pagination! Having conventions for cursor variables would make absolute sense and would even support sub pagination :)

**Comment by laughedelic** [comment]
Hi @gr2m! can I help here with anything? 

I use GraphQL pagination in a few places in my code and have this functionality reimplemeted a couple of times. It would be nice to have it as a reusable plugin.

**Comment by gr2m** [comment]
Absolutely! It’s all yours :) And you’d be perfect to build it as you have the real life examples as a test

**Comment by ericboucher** [comment]
If it helps, this is how we are implementing it for our github singer tap
https://github.com/MeltanoLabs/tap-github/pull/118

**Pull request closed without merging**
