### PR TITLE
fix(build): switch to esbuild

### PR DESCRIPTION
**Pull request by kfcampbell**
Replicating [octokit/request.js#584](https://github.com/octokit/request.js/pull/584) to another repo. 

---

Pika has been deprecated for a while now, and the project has now been archived, and because of that the released npm package is missing most of the files generated by the build step.

Uses esbuild to transpile the TS source code into an ESM source, NodeJs bundle, and a browser bundle

Uses the TypeScript compiler to generate the types.

### Before the change?

* Uses pika for the build system
* The released npm package is missing most of the files generated by the build step. `dist-node`, `dist-types`, `dist-web`... even though they are generated correctly.

### After the change?

* Uses esbuild to generate the JS bundles
* Uses the TypeScript compiler to generate the type definitions
* The correct file matching patterns are used so we publish all the necessary files again.

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
I can reproduce these build errors...I'm not sure what's going wrong in the build process yet.

**Comment by wolfy1339** [comment]
Is it a type that's imported? That would probably be the best guess

**Comment by kfcampbell** [comment]
Interestingly, the type is exported correctly from the .ts file as far as I can tell, but upon build, those types aren't present in the corresponding .js file. There may be an issue with the build process that's preventing the proper artifacts from being emitted.

**Comment by wolfy1339** [comment]
You need to explicitly mark the import for types.

Like so:
```ts
import type { Foo } from "bar";
```

**Comment by wolfy1339** [comment]
https://github.com/octokit/plugin-paginate-graphql.js/blob/81567468804b2466696c5b139ded894026b8a91e/src/index.ts#L5

That should be marked explicitly for type exports, the same way as for imports as listed above

**Comment by kfcampbell** [comment]
:facepalm: :facepalm: :facepalm: Thank you so much! I had clearly missed that.

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
